<?php

define ('TITLE_PODSERVER','PodServer');

define ('BIG_TITLE_POD_CONFIGURATION','Configuration and Quick Launch Pod');

define ('LABEL_PASSWORD','Password');

define ('BUTTON_LOGIN','Login');

define ('BUTTON_LOGOUT','Disconnect');

define ('ERROR_SSH_LOGIN_TRY_AGAIN','Update Password Incorrect Try again.');

define ('ENTER_PASSWORD_FOR_USER','Enter the password for user \'s');

define ('BUTTON_RECORD','Save');

define ('ACTION_TO_DO_CATCH_FIELD','You must enter the field');

define ('ACTION_TO_DO_CHECK_FIELD','You must activate the field');

define ('ACTION_TO_DO_SELECT_FIELD','You must select the field');

define ('TO_ACCESS_THIS_FIELD','to enter this field');

define ('THIS','Present');

define ('NONE','No');

define ('DELETE','Delete') ;

define ('UPLOAD_FILE_ERROR','Error \'s file upload');

define ('FILE_GENERATED_BY','file generated by');

define ('SYSTEM_TASK_IN_QUEUE','Task in the queue standby');

define ('TASK_COPY_FILE_CONFIG','Copy \'s file system configuration') ;

define ('TASK_COPY_FILE_ITEM','Copy \'s system sent file') ;

define ('ERROR_SSHLOGIN_INTO_SSHEXEC','Error in ssh login \'s execution of the order');

define ('ERROR_CAN_NOT_OPEN_CONFIG_PODSERVER_PHP','Couldn \'t open the "config/config-podserver.php" file');

define ('NO_METHOD_TO_RENDER_THIS_ITEM','This field type \'​​s not supported');


// Labels for tabs headers
$label_tab_network ="Network";
$label_tab_pod ="Pod";
$label_tab_general ="General";
$label_tab_mail ="Mail";
$label_tab_services ="Services";
$label_tab_administration ="Administration";
$label_tab_system ="System";
$label_tab_install ="Install";

// Labels and titles for network configuration
$label_title_network ="Network Configuration";
$label_local_ip ="Local IP Address";
$title_local_ip ="You must redirect HTTP and HTTPS port on your router to this address";
$label_gateway ="Gateway address";
$label_title_dyndns ="Configuring Dynamic Domain Name";
$label_dyndns_method ="DynDNS Provider";
$label_dyndns_login ="Login DynDNS";
$label_dyndns_pass ="Pass DynDNS";

// Labels and titles for pod configuration
$label_title_diasp ="Login to your Pod Diaspora *";
$label_domain_name ="Domain Name";
$label_pod_port ="Port used by Rails";
$label_pod_name ="Name Pod";
$label_title_ssl ="SSL Configuration";
$label_ssl_enable ="Enable SSL (recommended )";
$label_ssl_cert ="SSL certificate ( cert or crt. ).";
$label_ssl_key ="(SSL key . ) key";
$label_ssl_ca ="certificate authority ( ca ).";

// Labels and titles for general configuration
$label_title_general ="General Setup your Pod";
$label_jquery_enable ="Use jQuery via Google (recommended )";
$label_google_analytics_key ="Your key Google analytics";
$title_google_analytics_key ="This option allows you to track your visitor statistics using Google Analytics";
$label_enable_registrations ="Allow the inscription on the Pod";
$label_autofollow_on_join ="Follow a person for registration automatically";
$label_autofollow_on_join_user ="Person to follow automatically";
$label_invitation_enable ="Allow invitations";
$label_invitation_count ="Maximum number of invitation by user";
$label_paypal_hosted_button_id ="ID your PayPal donation button";
$title_paypal_hosted_button_id ="This option allows you to get a Paypal donation button to your name on your Pod";
$label_bitcoin_wallet_id ="ID your donate button Bitcoin";
$title_bitcoin_wallet_id ="This option allows you to get a donate button Bitcoin your name on your Pod";

// Labels and titles for mail setup
$label_title_mail ="Configuring mail settings";
$label_mail_enable ="Enable this feature";
$label_mail_method ="Method of mailing";
$label_sender_address ="Sender Address";
$label_smtp_host ="SMTP Host";
$label_smtp_port ="SMTP Port";
$label_smtp_authentication ="of SMTP authentication method";
$label_smtp_login ="ID";
$label_smtp_pass ="Password";
$label_mail_tls_auto ="Automatic TLS";
$label_mail_helo ="Host for HELO";
$label_openssl_verify_mode ="Negotiation mode OpenSSL";
$label_message_bus_api_key ="API Key (if method message bus )";

// Labels and titles for configuration services
$label_title_services ="Configure the services connected to your Pod";
$label_facebook_enable ="Enable Sharing on Facebook";
$label_facebook_key ="Key";
$label_facebook_secret ="Secret";
$label_twitter_enable ="Enable sharing on Twitter";
$label_twitter_key ="Key";
$label_twitter_secret ="Secret";
$label_tumblr_enable ="Enable sharing on Tumblr";
$label_tumblr_key ="Key";
$label_tumblr_secret ="Secret";
$label_wordpress_enable ="Enable sharing on Wordpress";
$label_wordpress_key ="Key";
$label_wordpress_secret ="Secret";

// Labels and titles for administration configuration
$label_title_diasp_admin ="Podmin Settings ( Administrator Pod )";
$label_admin_account ="User Podmin ( short identifier )";
$label_podmin_email ="email address Podmin";

// Labels and titles for system activities
$label_title_password_change ="Password for system users";
$label_f_pass_new ="New password";
$label_f_pass_conf ="Confirm password";
$label_sys_passchange ="Change Password";
$label_title_system_manage ="System Tools";
$label_sys_apply ="Apply configuration system";
$label_sys_restart ="Restart the appropriate services";
$label_sys_reboot ="Restart server";
$label_sys_shutdown ="Turning off the server";
$label_sys_update ="Update System";


// Labels for this install software configuration items
$label_DEF_SYST_USER_FOR_DIASPORA ="System User for Diaspora *";
$label_DEF_DIRECTORY_DIASPORA ="Installation Directory Diaspora *";
$label_DEF_DIRECTORY_SSL_CERTIFICATE ="System Directory for SSL certificates";
$label_DEF_FILE_NETWORK_INTERFACES ="System Network Configuration File";
$label_DEF_FILE_APACHE_VHOST ="apache configuration file ( VirtualHost )";
$label_DEF_FILE_DYNDNS ="Script Update Dynamic DNS";

?>
