<?
// File generated by PodServer Configuration
$action = "record";
$action_on_item = "undefined";
$local_ip = "192.168.0.50";
$gateway = "192.168.0.1";
$dyndns_method = "none";
$domain_name = "pod.wojtalik.be";
$pod_port = 3000;
$pod_name = "WojtaPod";
$db_host = "localhost";
$db_port = 3306;
$db_username = "";
$db_password = "";
$db_charset = "utf8";
$jquery_enable = "on";
$google_analytics_key = "";
$enable_registrations = "";
$autofollow_on_join = "on";
$autofollow_on_join_user = "";
$paypal_hosted_button_id = "";
$bitcoin_wallet_id = "";
$mail_enable = "on";
$mail_method = "sendmail";
$sender_address = "";
$smtp_host = "";
$smtp_port = "";
$smtp_authentication = "plain";
$smtp_login = "";
$smtp_pass = "";
$mail_helo = "";
$openssl_verify_mode = "none";
$message_bus_api_key = "";
$admin_account = "";
$podmin_email = "";
?>
